language: python
python:
  - 3.5
  
before_install:
  - sudo apt-get update
  - sudo apt-get install make
  - sudo apt-get install libgl1-mesa-glx -y
  - sudo apt-get install gcc gfortran -y

install:
  - pip install --upgrade pip
  - pip install -r requirements_dev.txt
  - pip install -e .

script:
  - pytest
